name: Cut Release
run-name: cut sdk release triggered by ${{ github.actor }}

#defaults:
#  run:
#    # run shell in interactive mode
#    shell: bash -ieo pipefail {0}

on:
  workflow_dispatch:
    inputs:
      bump-version-kind:
        type: choice
        required: true
        description: How to bump the current version
        default: devkind
        options:
          - "major"
          - "minor"
          - "patch"
          - "dev"
          - "devkind"
          - "pre"
          - "prekind"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout wandb/wandb
        uses: actions/checkout@v3
        with:
          repository: wandb/wandb
          path: wandb
      - name: Mergefreeze main branch
        run: |
          curl -d "frozen=true&user_name=${{ github.actor }}&note=prep for release" -X POST https://www.mergefreeze.com/api/branches/dmitryduev/mumbojumbo/main/?access_token=${{ secrets.COLDBEAR_TOKEN }}
          sleep 20
          curl -d "frozen=false&user_name=${{ github.actor }}&note=prep for release" -X POST https://www.mergefreeze.com/api/branches/dmitryduev/mumbojumbo/main/?access_token=${{ secrets.COLDBEAR_TOKEN }}

  run:
    name: Just run
    environment: "release"
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Sleep and Run
        run: |
          echo "Sleeping for 2"
          sleep 2
