name: Cut Release
run-name: cut sdk release triggered by ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      bump-kind:
        type: choice
        required: true
        description: How to bump the current version
        default: "PATCH"
        options:
          - "MAJOR"
          - "MINOR"
          - "PATCH"
#      ref:
#        type: string
#        required: false
#        description: The git ref to use for the release
#        default: main

jobs:
#  freeze:
#    name: Freeze main branch
#    runs-on: ubuntu-latest
#    steps:
#      - name: Freeze main branch
#        run: |
#          curl -d "frozen=true&user_name=${{ github.actor }}&note=prep for release" -X POST https://www.mergefreeze.com/api/branches/${{ github.repository }}/main/?access_token=${{ secrets.COLDBEAR_TOKEN }}

  test-nightly:
    name: Run nightly tests
#    needs: freeze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout wandb/wandb
        uses: actions/checkout@v3
        with:
          repository: wandb/wandb
          path: wandb
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run nightly tests
        run: |
          cd wandb
          pip install -e .
          CIRCLECI_TOKEN=${{ secrets.MUMBOJUMBO_TOKEN }} python tools/circleci-tool.py --dryrun trigger-nightly
          # CIRCLECI_TOKEN=${{ secrets.MUMBOJUMBO_TOKEN }} python tools/circleci-tool.py trigger-nightly --wait
          
  make-release:
    name: Prepare Release
    environment: "release"
    if: always()
    needs:
      - test-nightly
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.bump-version.outputs.release_version }}
      release-head-sha: ${{ steps.create-pr.outputs.pull-request-head-sha }}
    steps:
      - name: Checkout main for current release
        uses: actions/checkout@v3
#        with:
#          ref: ${{ github.event.inputs.ref }}
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install python dependencies
        id: install-python-deps
        run: |
          python -m pip install --upgrade pip
          pip install bump2version commitizen -U
      - name: Bump version and generate changelog entry with Commitizen (cz)
        id: cz
        run: |
          new_version="$(cz bump --increment ${{ github.event.inputs.bump-kind }} --yes --dry-run | grep bump | awk '{print $NF}')"
          echo "release_version=${new_version}" >> $GITHUB_OUTPUT
          echo "release_branch=release-${new_version}" >> $GITHUB_ENV
          echo "release_tag=v${new_version}" >> $GITHUB_ENV
          cz bump --increment ${{ github.event.inputs.bump-kind }} -ch --yes
#          git config --global user.email "github-actions[bot]@users.noreply.github.com"
#          git config --global user.name "github-actions[bot]"
      - name: Create release PR
        id: create-pr
        uses: peter-evans/create-pull-request@v4
        with:
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: ${{ env.release_branch }}
          delete-branch: true
          title: "chore(sdk): release ${{ steps.bump-version.outputs.release_version }} version"
          commit-message: "[create-pull-request] automated change of workflow ${{ github.run_id }} attempt ${{ github.run_number }}"
      - name: Create release notes
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          name: ${{ env.release_tag }}
          generateReleaseNotes: true
          tag: ${{ env.release_tag }}
          prerelease: false
          updateOnlyUnreleased: false
          commit: ${{ env.release_branch }}
    
  build-and-publish:
      name: Build and Publish
      environment: "release"
      runs-on: ubuntu-latest
      if: always()
      needs: make-release
      steps:
      - name: Checkout ${{  needs.make-release.outputs.release-head-sha }} for current release
        uses: actions/checkout@v3
        with:
          ref: ${{  needs.make-release.outputs.release-head-sha }}
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Build
        run: |
          # echo ${{ needs.make-release.outputs.output1 }}
          pip install wheel
          rm -rf dist build
          python setup.py sdist bdist_wheel
          ls -l dist
      - name: Publish
        run: |
          pip install twine
          twine upload --username=__token__ --password=${{ secrets.TEST_PYPI_TOKEN }} --repository testpypi dist/*
      - name: Test install
        run: |
          pip install --index-url https://test.pypi.org/simple/ --no-deps mumbojumbo
          version=`python -c "import mumbojumbo as mj; print(mj.__version__)"`
          if [ $version != ${{ needs.make-release.outputs.release-version }} ]; then
            echo "Version mismatch: $version != ${{ needs.make-release.outputs.release-version }}"
            exit 1
          fi

  post-release:
    name: Post Release Actions
    runs-on: ubuntu-latest
    needs: build-and-publish
    if: always()
    steps:
      - name: Bump version
        run: |
          # todo: checkout release branch 
          # todo: make bump-to-dev
          echo rofl
      - name: Merge Release PR to main & latest branches
        run: |
          # todo: set up git
          # todo: merge to main and latest
          echo lol

#  unfreeze:
#    name: Unfreeze main branch
#    needs: build-and-publish
#    if: always()
#    runs-on: ubuntu-latest
#    steps:
#      - name: Unfreeze main branch
#        run: |
#          curl -d "frozen=false&user_name=${{ github.actor }}&note=prep for release" -X POST https://www.mergefreeze.com/api/branches/${{ github.repository }}/main/?access_token=${{ secrets.COLDBEAR_TOKEN }}
